### PR TITLE
Add links based on content item

### PR DESCRIPTION
**Pull request by tijmenb**
This adds a bunch of useful links to the popup.

screen shot 2016-06-07 at 12 46 46

- An Edit-link that leads to the publishing application. For some applications we can infer a deeplink from the content_id (like collections-publisher). For others we either link to a prefilled search path (publisher) or link to the publishing app main page.
- Link to content-tagger (where anything can be tagged) and search-admin (where you can see what raw information rummager holds)
- Links to the rendering app was already available in the popup, but we now use the content item for this. This means that the link is also available on pages that 404, 410 and 5XX. Previously this link was based on a meta-tag which wouldn't be present on clobbered error pages.
- A similar link to the GitHub of the publishing application. In some cases this needs some mapping, because the `publishing_app` in content store isn't always the repo name. Make a PR if you find more exceptions.
- Link to the content schema on GitHub.
- A link to the brand new publishing-api debug page, which is initially only available in development (alphagov/publishing-api#345).

The way we generate these links is by fetching the content-item from the content-store when the user opens the popup. This means a slight delay between opening and the extension populating the menu.

I've re-organised the file/js layout to make it all easier to understand. The best way to review this may be by looking at the entire `/src` directory.

### CODE REVIEW

**Comment by elliotcm** [comment]
What's the rationale for what appears above or below the line?

**Comment by tijmenb** [comment]
The items above are based on base path, so you can switch between the pages - you can go from the `Content item (JSON)` to `On GOV.UK` and back again. 

The items below the line ("external links" I'm calling that) are not reversible in that way - you won't be able to go back to a content item from a GitHub repo. 

Above the line = open in same tab, below the line = open in new window.

**Comment by MatMoore** [comment]
👍 💯 

Maybe we could style the external links differently in a future PR, to distinguish them from the main ones.

**Comment by elliotcm** [comment]
Nice.

**Pull request merged**
