### PR TITLE
Release version 1.7.0

### PR DESCRIPTION
**Pull request by suzannehamilton**
- Allow user to switch A/B test buckets #45-#60
- Add link to document type documentation #61

https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments

@tijmenb: Should I delete the 1.6.0 zip, or do you want to keep the older versions around for people to download?

### CODE REVIEW

**Comment by tijmenb** [comment]
@suzannehamilton can you smuggle in https://github.com/alphagov/govuk-toolkit-chrome/pull/61?

**Comment by tijmenb** [comment]
@suzannehamilton I'd like to keep the old releases. Don't know how useful it is, but it seems like a good thing for auditing.

**Comment by suzannehamilton** [comment]
Yep, I've rebased and rerun `rake build` to include #61. 👍

**Comment by tijmenb** [comment]
I've uploaded the zip to the web store.

**Pull request merged**
