### PR TITLE
Release 1.11.1

### PR DESCRIPTION
**Pull request by andysellick**

### CODE REVIEW

**Comment by rubenarakelyan** [comment]
If https://github.com/alphagov/govuk-toolkit-chrome/pull/95 gets merged in time, it will be good to include it in this version.

**Comment by MatMoore** [comment]
@rubenarakelyan  #95 is now merged

**Comment by rubenarakelyan** [comment]
This will need to be rebuilt with the latest changes

**Comment by rubenarakelyan** [comment]
Done, ready for review

**Comment by tijmenb** [comment]
Rebuilt & force pushed.

**Pull request merged**
